# Generated by Django 4.1.1 on 2022-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заколовок"),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
